Much more verbose output, including instructions

diff --git a/vsafe b/vsafe
--- a/vsafe
+++ b/vsafe
@@ -7,7 +7,7 @@
 set -euo pipefail
 
 echo_error() {
-    echo "ERROR: $*"
+    echo "ERROR: $*" >&2
 }
 
 if ! which openssl > /dev/null; then
@@ -48,12 +48,40 @@ encrypt() {
     encrypted_payload_base64=$(encrypt_payload_base64 "$symmetric_key" "$input_file")
     encrypted_symmetric_key_base64=$(encrypt_symmetric_key_base64 "$symmetric_key" "$pubkey_file")
 
-    echo "# Dead simple asymmetric encryption file"
-    echo ""
-    echo "# RSA-Encrypted AES-256-CBC key"
-    echo "$encrypted_symmetric_key_base64"
-    echo "# AES-encrypted data payload"
-    echo "$encrypted_payload_base64"
+    cat <<EOF
+Dead simple asymmetric encryption file
+======================================
+
+RSA-Encrypted AES-256-CBC key
+-----------------------------
+
+symmetric_key=$encrypted_symmetric_key_base64
+
+AES-encrypted data payload
+--------------------------
+
+payload=$encrypted_payload_base64
+
+Decrypt via script
+------------------
+
+If you have been provided with a copy of the vsafe script, you can decode this
+message using your private key simply by
+
+    vsafe decrypt "\$privke_file" (this file) > decrypted-file
+
+Decrypt manually
+----------------
+
+You can decrypt the above using only openssl manually, so you do not have to
+trust vsafe’s own code. First, decrypt the symmetric key using your private key,
+
+    openssl rsautl -decrypt -oaep -inkey "\$privkey_file" -in <(echo "\$symmetric_key" | base64 --decode) > symmetric_key
+
+Now you can decrypt the payload,
+
+   openssl aes-256-cbc -d -in <(echo "\$payload" | base64 --decode) -pass stdin < symmetric_key > decrypted-file
+EOF
 }
 
 ###############################################
@@ -91,10 +119,15 @@ decrypt_file() {
     cmd=$(
         echo decrypt
         echo "$privkey_file"
-        cat "$encrypted_input_file" | grep -Ev '^($|#)'
+
+        symmetric_key_line=$(cat "$encrypted_input_file" | grep -E '^symmetric_key=')
+        echo "${symmetric_key_line#*=}"
+
+        payload_line=$(cat "$encrypted_input_file" | grep -E '^payload=')
+        echo "${payload_line#*=}"
     )
     if [[ $(echo "$cmd" | wc -l) -ne 4 ]]; then
-        echo "Encrypted data not in expected format"
+        echo_error "Encrypted data not in expected format"
         exit 4
     fi
     (
@@ -135,7 +168,7 @@ test_roundtrip_random_data() (
 
 test_real() (
     echo "Real test: Alice sends Bob a file"
-    self=$0
+    self=$(readlink -f "$0")
 
     workbench=$(mktemp --directory /dev/shm/vsafe-test_XXXXX)
     trap "rm -rf '$workbench'" EXIT
@@ -317,7 +350,6 @@ main() {
                 exit 11
             fi
             decrypt_file "$privkey_file" "$encrypted"
-            decrypt_help
             ;;
         keygen)
             shift
